### ISSUE TITLE
Change installation method for Caliper and add instalation for web3 in prerequisites.sh

### ISSUE THREAD

**Issue by ulalaa14** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#102]
# Task
## Detailed Description
Currently our prerequisites.sh file installing Caliper using Global NPM method. However this method not working well in practical. We need to change using Local NPM method and put Caliper inside folder workload.

Another package that need to install is web3. This web3 should installed inside workload folder too. 
## Associated story
-
## Notes
Improvement from current prerequisites.sh file

**Comment by XhorxhinaT** [comment]
Finished. The last PR
