### ISSUE TITLE
Test OptiBench clean installation

### ISSUE THREAD

**Issue by fayanpardo** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#111]
# Task
## Detailed Description
We need to test a clean installation of our tool in order to make sure that users can use without problems.
## Acceptance Criteria 

- [ ] The tool runs correctly after a clean installation.

**Comment by fayanpardo** [comment]
I have tested this in an EC2 machine. Several things to take into account:

- We should check if pip3 is installed or at least write in the README the requirement (may be better the latest). A possible solution is to guide the user to create a python virtual environment in the README.

- gcloud init seemed too annoying for me in case i needed to re run prerequisite script. Maybe we should ask the user to execute it instead of running it ourselves. A possible solution is to not run this command and indicate the user in the echo to make sure to run it.

**Comment by ulalaa14** [comment]
I put code for checking pip3 and python3 (if not found just urge user to installing it first and skip the library installation to run) in prerequisite . for venv actually a good approach, but how does it behave with our code? in the code should we define path where we call the library ? if not it's good, if yes then we have to change our code

**Comment by ulalaa14** [comment]
I've run the clean testing. I put it in Word file. At the end the benchmark was crashed. but there are also several errors (but the command still running) and the gas limit is huge. For the report there is error missing blueplot.html
[Clean Testing Optibench.docx](https://github.com/Cloud-Prototyping-WS-2019-20/cp_ws_1920/files/4178467/Clean.Testing.Optibench.docx)

execution time: around 1.5 hours

**Comment by ulalaa14** [comment]
related with the prerequisite, I found out that Puppeth & Geth are okay to be installed by our tool. since their documentation was a little bit confusing

**Comment by ankushshr1993** [comment]
> gcloud init seemed too annoying for me in case i needed to re run prerequisite script. Maybe we should ask the user to execute it instead of running it ourselves. A possible solution is to not run this command and indicate the user in the echo to make sure to run it.

Just wanted to confirm if the issue was related the attached screen shot 
that while re running the prerequisite script even if a user is logged in with gcloud auth it's still requesting for authentication @boxrhcp 

<img width="626" alt="Screenshot 2020-02-10 at 16 48 19" src="https://user-images.githubusercontent.com/38669738/74165264-2961d600-4c25-11ea-9675-e5ded8e0e368.png">

**Comment by fayanpardo** [comment]
> I've run the clean testing. I put it in Word file. At the end the benchmark was crashed. but there are also several errors (but the command still running) and the gas limit is huge. For the report there is error missing blueplot.html
> [Clean Testing Optibench.docx](https://github.com/Cloud-Prototyping-WS-2019-20/cp_ws_1920/files/4178467/Clean.Testing.Optibench.docx)
> 
> execution time: around 1.5 hours

@ulalaa14 about the "geth command not found" is fixed in the last merge. VMs needed more time to be built. The error of the huge gas limit needs more info. What is the error that caliper is printing under caliper-status.txt?

**Comment by fayanpardo** [comment]
> > gcloud init seemed too annoying for me in case i needed to re run prerequisite script. Maybe we should ask the user to execute it instead of running it ourselves. A possible solution is to not run this command and indicate the user in the echo to make sure to run it.
> 
> Just wanted to confirm if the issue was related the attached screen shot
> that while re running the prerequisite script even if a user is logged in with gcloud auth it's still requesting for authentication @boxrhcp
> 
> <img alt="Screenshot 2020-02-10 at 16 48 19" width="626" src="https://user-images.githubusercontent.com/38669738/74165264-2961d600-4c25-11ea-9675-e5ded8e0e368.png">

@ankushshr1993 
Correct!

**Comment by ulalaa14** [comment]
> > I've run the clean testing. I put it in Word file. At the end the benchmark was crashed. but there are also several errors (but the command still running) and the gas limit is huge. For the report there is error missing blueplot.html
> > [Clean Testing Optibench.docx](https://github.com/Cloud-Prototyping-WS-2019-20/cp_ws_1920/files/4178467/Clean.Testing.Optibench.docx)
> > execution time: around 1.5 hours
> 
> @ulalaa14 about the "geth command not found" is fixed in the last merge. VMs needed more time to be built. The error of the huge gas limit needs more info. What is the error that caliper is printing under caliper-status.txt?

i caught this message in caliper.log because caliper-status.txt already deleted i haven't managed to saw it.
![image](https://user-images.githubusercontent.com/16094968/74178830-87e67e80-4c3c-11ea-923a-a3123d07d7ea.png)
i also can attach the caliper.log if you wanted to check it out:
[caliper.log](https://github.com/Cloud-Prototyping-WS-2019-20/cp_ws_1920/files/4182502/caliper.log)

**Comment by fayanpardo** [comment]
> > > I've run the clean testing. I put it in Word file. At the end the benchmark was crashed. but there are also several errors (but the command still running) and the gas limit is huge. For the report there is error missing blueplot.html
> > > [Clean Testing Optibench.docx](https://github.com/Cloud-Prototyping-WS-2019-20/cp_ws_1920/files/4178467/Clean.Testing.Optibench.docx)
> > > execution time: around 1.5 hours
> > 
> > 
> > @ulalaa14 about the "geth command not found" is fixed in the last merge. VMs needed more time to be built. The error of the huge gas limit needs more info. What is the error that caliper is printing under caliper-status.txt?
> 
> i caught this message in caliper.log because caliper-status.txt already deleted i haven't managed to saw it.
> ![image](https://user-images.githubusercontent.com/16094968/74178830-87e67e80-4c3c-11ea-923a-a3123d07d7ea.png)
> i also can attach the caliper.log if you wanted to check it out:
> [caliper.log](https://github.com/Cloud-Prototyping-WS-2019-20/cp_ws_1920/files/4182502/caliper.log)

I guess caliper.log needs to be cleaned because there are several runs written. I see a success benchmark and a failure one.
From the failure I have 2 guesses:

1.  The caliper bind did not work

1.  Your IP is not accepted in GCP firewall.

**Comment by ulalaa14** [comment]
I think it does several runs because it was in the loop or? that's why there a lot of things going on. and for binding I guess it's working since there are results. but for IP, i already put mine on the VPC Firewall rules. probably the connection is unstable
