### ISSUE TITLE
Finish Final Presentation

### ISSUE THREAD

**Issue by fayanpardo** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#113]
# Task
## Detailed Description
We need to prepare and finish the final presentation
## Acceptance Criteria

- [ ] Create the final presentation

**Comment by SantoshDhirwani** [comment]
https://docs.google.com/presentation/d/1bH9aCOqzMVPamoNdoFWi7aNdaUboUWaN8Bsu8U6wBzs/edit#slide=id.g6e8dd92098_3_0
