### ISSUE TITLE
Research bootnode metadata/information

### ISSUE THREAD

**Issue by fayanpardo** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#15]
# Task
## Detailed Description
We need to know if the bootnode gathers information of the nodes already connected in the network. If it gathers the information, we want to know if we can somehow retrieve it and use it in a script. This will be needed for the SUT deployment script.
## Associated story
Story: #13 Ethereum SUT Deployment
## Notes
The research should be documented commenting in this issue with the sources found. If possible, suggest a way of applying the solution.

**Comment by eltalkarim** [comment]
https://ethereum.stackexchange.com/questions/2230/get-a-peer-list-for-my-geth-node

**Comment by eltalkarim** [comment]
I am not sure if we can query the bootnode actually. But we can definity talk to any peer

**Comment by XhorxhinaT** [comment]
https://github.com/ethereum/go-ethereum/wiki/Management-APIs#admin_peers
https://github.com/ethereum/go-ethereum/wiki/Setting-up-private-network-or-local-cluster
https://github.com/ethereum/go-ethereum/blob/master/params/bootnodes.go
https://www.youtube.com/watch?v=49KK8MbMggQ
https://github.com/ethereum/go-ethereum/issues/3703

**Comment by eltalkarim** [comment]
Hello @XhorxhinaT , I see you did some research.  What are you trying to say with these links? Did you find a way to query the bootnode to get some metadata?

**Comment by fayanpardo** [comment]
Good Job! Group decision: not to depend on bootnode information to automate the addition of sealers when building the SUT
