### ISSUE TITLE
Research how to dynamically public miner nodes services in the same cluster

### ISSUE THREAD

**Issue by fayanpardo** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#16]
# Task
## Detailed Description
The idea is to use a script that uses Google SDK to connect to GKE and manage the SUT. We need to know if, after deploying with Kubernetes the SUT in the same cluster, we can receive an event warning us the the nodes have been correctly deployed. This will be needed to know when to accept a new sealer node in the network. 
GKE will create containers in a cluster, the idea is that we will have one node per container. Theoretically the nodes will be built in the same machine, which means that these can not use the same ports. However with GKE we have the possibility of publishing services to access containers that can have different IP:Ports addresses even if they are in the same cluster/machine. We need to know if the use of services can solve our problem of publishing the Ethereum nodes even if these are in the same cluster.
## Associated story
Story: #13 Ethereum SUT Deployment
## Notes
The research should be documented commenting in this issue with the sources found. If possible, suggest a way of applying the solution.

**Comment by eltalkarim** [comment]
The story description is vague. What the problem you are trying to solve? what is the appraoch? Is there an architecture behind it?

**Comment by fayanpardo** [comment]
> The story description is vague. What the problem you are trying to solve? what is the appraoch? Is there an architecture behind it?

Agree, hopefully is more clear now

**Comment by fayanpardo** [comment]
Workaround to know when nodes are correctly deployed if event based notification is not found:
`kubectl get deployment [DEPLOYMENT] -n [NAMESPACE] -o yaml`
This gives all the information of the deployment, in it we can find the section "status":

> status:
>   availableReplicas: 1
>   conditions:
>   - lastTransitionTime: "2019-12-13T18:23:46Z"
>     lastUpdateTime: "2019-12-13T18:23:46Z"
>     message: Deployment has minimum availability.
>     reason: MinimumReplicasAvailable
>     **status: "True"
>     type: Available**
>   - lastTransitionTime: "2019-12-13T18:23:25Z"
>     lastUpdateTime: "2019-12-13T18:23:46Z"
>     message: ReplicaSet "eth-bootnode-5c9b65455d" has successfully progressed.
>     reason: NewReplicaSetAvailable
>     status: "True"
>     type: Progressing
>   observedGeneration: 1
>   readyReplicas: 1
>   replicas: 1
>   updatedReplicas: 1

The idea would be to query this information every x seconds with a timeout try number.

**Comment by fayanpardo** [comment]
To make a node (container) access public we need to publish a service https://cloud.google.com/kubernetes-engine/docs/how-to/exposing-apps

Specifically NodePort type let you open a port of a pod (node): https://kubernetes.io/docs/concepts/services-networking/service/#nodeport

It can be a possible solution, the limitation is that the public port range range is 30000-32767.
Example test:

- Deploy deployment. This deployment will create 3 pods (nodes) with the same image.

> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: my-deployment-50000
> spec:
>   selector:
>     matchLabels:
>       app: metrics
>       department: engineering
>   replicas: 3
>   template:
>     metadata:
>       labels:
>         app: metrics
>         department: engineering
>     spec:
>       containers:
>       - name: hello
>         image: "gcr.io/google-samples/hello-app:2.0"
>         env:
>         - name: "PORT"
>           value: "8545"

- Deploy service

> apiVersion: v1
> kind: Service
> metadata:
>   name: my-np-service
> spec:
>   type: NodePort
>   selector:
>     app: metrics
>     department: engineering
>   ports:
>   - protocol: TCP
>     port: 8545
>     nodePort: 30000
>     targetPort: 8545

- Open NodePort in firewall (can be done via CLI or via UI)

`gcloud compute firewall-rules create test-node-port --allow tcp:30000`

- Access to one pod with [Pod-external-ip]:[nodeport] you can obtain pod public IP with

`kubectl get nodes --output wide`
