### ISSUE TITLE
[SUT Deployment Script] Script to deploy the SUT container images

### ISSUE THREAD

**Issue by fayanpardo** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#17]
# Task
## Detailed Description
We need a script that deploys the Ethereum SUT. 
This part of the script should take the container images published in Google Container Registry and use them to deploy the SUT. 
The nodes should be accessible through an IP and port.
This script should receive as parameter the number of nodes, the block gas limit and block interval. 
## Associated story
Story: #13 Ethereum SUT Deployment
## Notes
First step of this task should be to create the YAML Kubernetes template for the deployment of nodes
## Help sources
https://imti.co/ethereum-kubernetes/
https://cloud.google.com/container-registry/docs/using-with-google-cloud-platform#google-kubernetes-engine

**Comment by fayanpardo** [comment]
We may need to add the flag 
`--trace value                       Write execution trace to the given file`
in the geth commands of the images. There is no current way to see if the processes are really executing in GKE.

**Comment by SantoshDhirwani** [comment]
@boxrhcp  Maybe this can help:

https://medium.com/google-cloud/ethereum-on-google-cloud-platform-8f10c82493ca
