### ISSUE TITLE
Mockup script to find the optimal value of block gas limit and block interval.

### ISSUE THREAD

**Issue by fayanpardo** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#20]
# Task
## Detailed Description
We need a script that reads the results of the experiment and finds the optimal values.
Specifically this mockup script can read for now from a file fake experiment results (block gas limit, block interval, throughput) and it must find minimum the block gas limit and block interval values that offer the maximum improvement.
The script also receives the sensitivity configuration parameter (minimum difference value of improvement to keep searching for optimal values).
**Find the mathematical value for parameters value to test, by researching about operational research**

## Associated story
Story: #14 Block gas limit and block interval optimal values
## Notes 
This story can benefit from the results of #19

**Comment by ulalaa14** [comment]
how is the sensitvity works? what does it do?

**Comment by ulalaa14** [comment]
source inspiration: http://hplgit.github.io/primer.html/doc/pub/dictstring/._dictstring-solarized004.html

**Comment by ulalaa14** [comment]
find the mathematical value for parameters value to test, by researching about operational research

**Comment by fayanpardo** [comment]
We can start analyzing the data generated and to find the optimal parameter with bilinear interpolation.
Source:
https://en.wikipedia.org/wiki/Bilinear_interpolation
https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp2d.html

Ideally to maximize the function obtained from this method

Here is an example of how to minimize a function (not useful but we need something similar)
https://stackoverflow.com/questions/34776435/finding-minimum-of-interpolated-function

**Comment by fayanpardo** [comment]
We are following the algorithm proposed in #76
