### ISSUE TITLE
Modify aggregate-reports script to create a file with a grid of results.

### ISSUE THREAD

**Issue by fayanpardo** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#58]
# Task
## Detailed Description
In order to make easier the implementation of calculate-optimal-values.py added in #57, we need to modify aggregate-html-reports.py to generate file with a grid of the results.
This script should receive as parameters the maximum and minimum values of both block interval and block gas limit and their steps. Then for each function in the workload benchmarked (for now open and transfer) it should create a file with a grid of results. This grid should have same number of rows and columns as block gas limit and block interval respectively, separated in comas and line jumps.
Results must be organized correctly in the grid. Imagine 3x3 example:
min gas limit = 10m, max gas limit = 20m, gas limit step = 5m
min interval = 10, max interval = 20, interval step = 5
The result is organized this way (x= gas limit, y= interval)
.........10,15,20 
10m   15,17,19
15m   25,27,29
20m   30,32,34

Being the file output this format:
15,17,19
25,27,29
30,32,34
## Associated story
#14 #57

**Comment by XhorxhinaT** [comment]
Idk if u mean just a simple print out in grid

def print_grid(grid):
    for row in grid:
        for e in row:
            print (e, end=""),
   #print_grid(grid_maker_valueOfthroughpout(3, 3))
