### ISSUE TITLE
[Benchmark Algorithm] Implement algorithm to find the last improvement configuration value

### ISSUE THREAD

**Issue by fayanpardo** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#65]
# Task
## Detailed Description
We suppose that the user does not have knowledge about what is the configuration of block gas limit and block interval where he can have no more improvement.
Our tool should by benchmarking find these last improvement configuration values. 
A new configuration variable should be added in the config file to indicate the minimum performance improvement difference.
E.g. If the config value is 5, the algorithm should stop after seeing less than 5% improvement between benchmarks.
We need to implement this algorithm in main.py.
## Acceptance Criteria
- [ ] The code of the script runs without any errors (error handling correctly used)
- [ ] The script must be able to detect the block gas limit and block interval configuration where no more throughput improvement is found, taking into account the difference value from the config file.

## Associated story
#13

**Comment by eltalkarim** [comment]
We have managed to put the algorithm in a flowchart:
https://www.lucidchart.com/invitations/accept/981a2b20-5dd7-47b9-afca-46a245cadc1c
https://www.lucidchart.com/invitations/accept/f02b9756-b737-473c-b96a-65208cbd6af5
