### ISSUE TITLE
Create a first draft for the final presentation

### ISSUE THREAD

**Issue by SantoshDhirwani** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#93]
# Task

## Detailed Description

We need to create a first draft for the final presentation so we can get some early feedback from Jacob in the next meeting (04.02.2020).

## Acceptance Criteria

- [x]  The presentation must have a structure

- [ ]  It must have all content which is more or less ready, for example,  all of the theoretical content, system design, etc.-ON HOLD  due to results

**Comment by XhorxhinaT** [comment]
https://docs.google.com/presentation/d/1bH9aCOqzMVPamoNdoFWi7aNdaUboUWaN8Bsu8U6wBzs/edit?usp=sharing  The Structure is done!
After discussing it, the images of codes will be add and the **results+conclusions are still ON-HOLD**

**Comment by XhorxhinaT** [comment]
@boxrhcp @ulalaa14 @ankushshr1993 @SantoshDhirwani @eltalkarim
