### ISSUE TITLE
Modify Script aggregate-results to create a meaningful report

### ISSUE THREAD

**Issue by fayanpardo** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#94]
# Task
## Detailed Description
Right now main.py script is giving the final result in a print command. We need to generate a meaningful report to the final user where he can see the final output of our tool and meaningful insights of our execution.
The idea is to modify aggregate-results so that it creates a HTML format report with the information of our execution, plotting useful graphs.
## Aceptance criteria

- [x] The script must run without errors

- [x] Once the execution of the tool is finished a report in HTML should be available to open and see the result and meaningful insights of our execution.

## Associated story
#14

**Comment by ankushshr1993** [comment]
@boxrhcp please help me understand the following points better

1. In which specific script are we getting  " final result in a print command"
2. Describe a bit more about generating a "meaningful report to the final user "  through meaningful insights of our execution and useful graphs.
3. Is HTML a condition or can we generate a PDF also?

If needed we can discuss this offline too.

**Comment by fayanpardo** [comment]
1. In main.py script, but it can be seen in #88 which should be merged soon.
2. I am not an expert of visualizing data so in this task we need to find out a meaningful way to represent data. First thought that comes into my mind is create a graph with the different results for each combination of block interval and block gas limit, show table of our different results, etc. But I'm sure you are more creative than me with python :)
3. Better an HTML, even a static site can be more flexible for further development and interactive for the final user than a PDF.

**Comment by fayanpardo** [comment]
As discussed, add to PR #103 the execution time in the homepage, new section with configuration information and a section per interval to see plots with the gas limit evolution
